-- 쿠팡 SKU 마스터에서 추출한 색상/옵션수 보강 (제품명 매칭)
-- 생성: 315개 제품 / 카탈로그 369개

update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '듀오 매트 그레인 마그넷 링크 실리콘 스트랩 14mm';
update public.products set color_count = 19, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크, 퍼플, 브라운, 베이지' where name = '오리진 실리콘 스트랩 18mm';
update public.products set color_count = 20, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 옐로우, 핑크, 퍼플, 브라운, 베이지' where name = '모노 스트랩 (스포츠루프)';
update public.products set color_count = 15, color = '블랙, 네이비, 블루, 그린, 레드, 오렌지' where name = '풀탭 스포츠루프 스트랩';
update public.products set color_count = 6, color = '블랙, 화이트, 네이비, 블루, 그린' where name = '마일드 트레일 루프 스트랩';
update public.products set color_count = 12, color = '화이트, 그레이, 그린, 오렌지, 베이지' where name = '후크형 트레일 패브릭 나일론 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 그린, 오렌지' where name = '알파인 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지' where name = '후크 투톤 패브릭 나일론 스트랩 (*구 알파인 루프 스트랩 리뉴얼 형)';
update public.products set color_count = 14, color = '블랙, 화이트, 그레이, 실버, 네이비, 그린, 레드' where name = '(버클형)마그넷 브레이드 스트랩';
update public.products set color_count = 134, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 핑크, 퍼플, 브라운' where name = '버클형 파스텔 스트랩';
update public.products set color_count = 20, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 브라운' where name = '버클 브레이드 스트랩';
update public.products set color_count = 10, color = '블랙, 그레이, 네이비, 블루, 그린, 오렌지, 퍼플' where name = '니트 스트랩';
update public.products set color_count = 17, color = '블랙, 화이트, 그레이, 실버, 네이비, 그린, 레드, 오렌지, 핑크, 베이지' where name = '프리미엄 마그네틱 버클형 브레이드 스트랩';
update public.products set color_count = 3, color = '블랙, 그레이, 네이비' where name = '나토 밴드';
update public.products set color_count = 15, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플, 베이지' where name = '베이직 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 옐로우, 퍼플' where name = '버튼 베이직 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 옐로우, 핑크' where name = '스포티 실리콘 스트랩';
update public.products set color_count = 50, color = '블랙, 화이트, 그레이, 실버, 블루, 그린, 레드, 오렌지, 옐로우' where name = '버튼형 스포티 스트랩';
update public.products set color_count = 28, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크, 베이지' where name = '어반 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 핑크, 베이지' where name = '디버클 마그네틱 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 레드, 오렌지, 핑크, 베이지' where name = '소프트 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 오렌지, 핑크, 퍼플' where name = '와플 패턴 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 옐로우, 핑크, 퍼플, 베이지' where name = '스트릿 엣지 실리콘 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 실버, 네이비, 그린, 오렌지, 핑크, 베이지' where name = '디버클 블랜드 투톤 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지' where name = '디버틀 오션 실리콘 스트랩';
update public.products set color_count = 14, color = '블랙, 그레이, 실버, 골드, 블루, 그린, 레드, 오렌지, 퍼플, 브라운' where name = '메탈 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 골드, 핑크' where name = '버클형 슬림 메탈 밀레니즈 스트랩';
update public.products set color_count = 6, color = '블랙, 화이트, 실버, 골드, 핑크' where name = '일반형 디버클 마그네틱 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '스틸 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '슬림 스틸 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '쥬빌레 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '큐빅 글리터 메탈 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드' where name = '체인 큐빅 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '체인 스틸 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '헤링본 큐빅 메탈 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드, 핑크' where name = '샤인 큐빅 메탈 스트랩';
update public.products set color_count = 2, color = '실버, 골드' where name = '샤인 큐빅 슬림 브레이슬릿 스트랩';
update public.products set color_count = 1, color = '골드' where name = '샤인 큐빅 트리플 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '더블 라인 큐빅 메탈 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드' where name = '스퀘어 체인 메탈 스트랩';
update public.products set color_count = 4, color = '블랙, 화이트, 브라운, 베이지' where name = '싱글 체인 레더 스트랩';
update public.products set color_count = 1, color = '골드' where name = '레더 체인 스틸 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '일반형 싱글 투어 가죽 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '슬림 레더 가죽 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '디버클 슬림 레더 가죽 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '모던 레더 가죽 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '빈티지 레더 가죽 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '가죽 링크 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '코도반 가죽 레더 스트랩';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 블루, 그린' where name = '컴포트 핏 버클 나일론 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드' where name = '모노핏 프리미엄 마그네틱 버클 나일론 스트랩';
update public.products set color_count = 10, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '에어핏 스포츠 버튼 투톤 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크' where name = '블랙 버클 펀칭 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 실버, 블루, 그린, 레드, 옐로우, 핑크, 퍼플' where name = '에어 위브 프리미엄 마그네틱 버클 나일론 스트랩';
update public.products set color_count = 26, color = '블랙, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크, 퍼플, 베이지' where name = '에어 슬로프 밸크로 패브릭 나일론 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 네이비, 블루, 그린, 레드, 옐로우, 퍼플, 브라운, 베이지' where name = '포우 레더 메탈 버클 마그넷 링크 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 그린, 오렌지, 옐로우, 핑크' where name = '투톤 베이직 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 핑크' where name = '스무스 릿지 실리콘 스트랩';
update public.products set color_count = 21, color = '블랙, 화이트, 네이비, 블루, 레드, 핑크, 브라운' where name = '크로코 클래식 포우 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 옐로우' where name = '스퍼트 투톤 버클 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '트위스트 체인 메탈 스트랩';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 그린, 레드, 오렌지, 퍼플, 베이지' where name = '러너 스피드 실리콘 스트랩';
update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '매트 그레인 마그넷 링크 실리콘 스트랩 20mm';
update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '듀오 매트 그레인 마그넷 링크 실리콘 스트랩 20mm';
update public.products set color_count = 6, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드' where name = '듀오링 스포츠 나일론 스트랩 (*기종별)';
update public.products set color_count = 12, color = '블랙, 오렌지, 핑크, 투명' where name = '투명 크리스탈 스트랩 20mm';
update public.products set color_count = 10, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '투톤 펀칭 실리콘 스트랩 22mm';
update public.products set color_count = 32, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 핑크' where name = '버튼 스포티 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 핑크, 베이지' where name = '디버클 마그네틱 스포티 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크' where name = '펀칭 실리콘 스트랩 (*실버 버클)';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 레드, 오렌지, 핑크, 퍼플, 베이지' where name = '디버클 오션 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 실버, 네이비, 그린, 레드, 오렌지, 핑크, 퍼플' where name = '브레이드 스트랩';
update public.products set color_count = 161, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크, 퍼플, 베이지' where name = '마그넷 브레이드';
update public.products set color_count = 12, color = '블랙, 실버, 네이비, 그린, 레드, 오렌지, 핑크, 퍼플' where name = '마그넷 루프 스트랩';
update public.products set color_count = 22, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플, 베이지' where name = '스트래치 나일론 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 골드, 핑크' where name = '(버클) 슬림 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '스틸 스트랩 (*구버전)';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '쥬빌레 스틸 스트랩';
update public.products set color_count = 1, color = '골드' where name = '샤인 큐빅 트리플 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '싱글 투어 레더 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 그린, 레드, 옐로우, 핑크, 퍼플, 브라운' where name = '슬림 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 그레이, 네이비, 그린, 오렌지, 옐로우, 브라운' where name = '빈티지 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '마그네틱 디버클 슬림 레더 스트랩';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 블루, 그린' where name = '컴포트 핏 버클 나일론 실리콘 스트랩 22mm';
update public.products set color_count = 5, color = '블랙, 그레이, 블루, 그린, 오렌지' where name = '컴포트 핏 디버클 나일론 실리콘 스트랩 22mm';
update public.products set color_count = 12, color = '블랙, 그레이, 네이비, 블루, 그린, 옐로우, 베이지' where name = '브리즈 포우 레더 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 네이비, 블루, 그린, 레드, 옐로우, 퍼플, 브라운, 베이지' where name = '포우 레더 메탈 버클 마그넷 링크 스트랩 22mm';
update public.products set color_count = 12, color = '블루, 그린, 옐로우, 핑크, 퍼플, 투명' where name = '퓨어 글리터 젤리 투명 스트랩 22mm';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 옐로우' where name = '스퍼트 투톤 버클 실리콘 스트랩 22mm';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지' where name = '후크 투톤 패브릭 나일론 스트랩 22mm (*구 알파인루프 디자인)';
update public.products set color_count = 22, color = '블랙, 그레이, 실버, 블루, 그린, 오렌지, 옐로우, 핑크, 브라운, 베이지' where name = '듀얼 쉐이드 마그네틱 실리콘 스트랩 22mm';
update public.products set color_count = 32, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 핑크' where name = '오션 실리콘 스트랩 22mm';
update public.products set color_count = 10, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '런 스플릿 투톤 실리콘 스트랩 22mm';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 브라운' where name = '에어 그리드 애슬레틱 버튼 실리콘 스트랩 22mm';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 브라운' where name = '버티컬 그리드 애슬레틱 실리콘 스트랩 22mm';
update public.products set color_count = 1, color = '그레이, 블루' where name = '플렉스 니트 하이브리드 버클 나일론 실리콘 스트랩 22mm';
update public.products set color_count = 5, color = '블랙, 그레이, 블루, 그린, 오렌지' where name = '데님 스티치 하이브리드 디버클 나일론 실리콘 스트랩 22mm';
update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '매트 그레인 마그넷 링크 실리콘 스트랩 22mm';
update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '듀오 매트 그레인 마그넷 링크 실리콘 스트랩 22mm';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 블루, 그린' where name = '블로키 메탈 버클 실리콘 스트랩 22mm';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 블루, 그린' where name = '매시브 메탈 버클 실리콘 스트랩 22mm';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 옐로우' where name = '투톤 블로키 버클 실리콘 스트랩 22mm';
update public.products set color_count = 9, color = '블랙, 화이트, 네이비, 블루, 그린, 레드, 옐로우, 퍼플, 브라운, 베이지' where name = '와이트릭 마그넷 링크 메탈 스트랩 22mm';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 레드, 오렌지, 핑크, 베이지' where name = '세그먼트 마그넷 링크 실리콘 스트랩 22mm';
update public.products set color_count = 12, color = '블랙, 오렌지, 핑크, 투명' where name = '투명 크리스탈 스트랩 22mm';
update public.products set color_count = 10, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '러닝 마스터 스포츠 실리콘 스트랩 22mm';
update public.products set color_count = 22, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플, 베이지' where name = '듀오링 스포츠 나일론 스트랩 22mm';
update public.products set color_count = 7, color = '블랙, 실버, 골드' where name = '알파 프레스티지 스틸 스트랩 22mm';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지' where name = '후크 투톤 패브릭 나일론 스트랩 24mm';
update public.products set color_count = 8, color = '블랙' where name = '알파 프레스티지 스틸 스트랩 *구_ 스틸 스트랩';
update public.products set color_count = 1 where name = '플렉서블 링크 프레스티지 티타늄 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드' where name = '플렉서블 링크 프레스티지 스틸 스트랩';
update public.products set color_count = 134, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 핑크, 퍼플, 브라운' where name = '브레이드 솔로루프 스트랩';
update public.products set color_count = 10, color = '그레이, 네이비, 블루, 그린, 레드, 오렌지, 브라운' where name = '트레일 스포츠 루프';
update public.products set color_count = 12, color = '블랙, 실버, 네이비, 그린, 레드, 오렌지, 핑크, 퍼플' where name = '밀레니즈 루프 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 골드, 핑크' where name = '슬림 밀레니즈 루프 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '모던 핏 스틸 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '프리미엄 슬림 모던 핏 스틸 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '쥬빌레 스트랩';
update public.products set color_count = 3, color = '블랙, 실버, 골드' where name = '슬림 쥬빌레';
update public.products set color_count = 4, color = '블랙, 화이트, 브라운, 베이지' where name = '클리어 체인 스트랩';
update public.products set color_count = 2, color = '블랙, 골드' where name = '일체형 클리어 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드, 핑크' where name = '크리스탈 큐빅 브레이슬릿 스트랩';
update public.products set color_count = 12, color = '블랙, 오렌지, 핑크, 투명' where name = '크리스탈 큐빅 스트랩';
update public.products set color_count = 4, color = '블랙, 화이트, 브라운, 베이지' where name = '체인 모던핏 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지' where name = '오션 실리콘 스트랩';
update public.products set color_count = 2, color = '핑크, 퍼플' where name = '버튼 실리콘 스트랩';
update public.products set color_count = 20 where name = '매트 그레인 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 8 where name = '베이직 버클 실리콘 스트랩';
update public.products set color_count = 6 where name = '모션 트레드 버클 실리콘 스트랩';
update public.products set color_count = 44 where name = '디버클 마그네틱 메쉬홀 실리콘 스트랩';
update public.products set color_count = 12 where name = '프리미엄 마그네틱 버클 브레이드 스트랩';
update public.products set color_count = 4 where name = '갤럭시 워치8 호환 샤인 큐빅 메탈 스트랩';
update public.products set color_count = 10, color = '블랙, 실버, 골드, 핑크' where name = '갤럭시 워치8 클래식 샤인 큐빅 메탈 스트랩';
update public.products set color_count = 2, color = '실버, 골드' where name = '갤럭시 워치8 호환 샤인 큐빅 슬림 브레이슬릿 스트랩';
update public.products set color_count = 2, color = '실버, 골드' where name = '갤럭시 워치8 클래식 샤인 큐빅 슬림 브레이슬릿 스트랩';
update public.products set color_count = 4 where name = '갤럭시 워치8 호환 체인 스틸 스트랩';
update public.products set color_count = 3, color = '실버, 골드' where name = '갤럭시 워치8 클래식 체인 스틸 스트랩';
update public.products set color_count = 4 where name = '갤럭시 워치8 호환 레더 체인 스틸 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 블루, 핑크, 브라운, 베이지' where name = '갤럭시 워치8 클래식 레더 체인 스틸 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드, 핑크' where name = '갤럭시 워치8 호환 샤인 큐빅 트리플 스트랩';
update public.products set color_count = 4 where name = '갤럭시 워치8 호환 싱글 체인 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운' where name = '갤럭시 워치8 클래식 싱글 체인 레더 스트랩';
update public.products set color_count = 8 where name = '갤럭시 워치8 호환 싱글 투어 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운' where name = '갤럭시 워치8 클래식 싱글 투어 레더 스트랩';
update public.products set color_count = 20 where name = '갤럭시 워치8 호환 슬림 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '갤럭시 워치8 클래식 호환 슬림 레더 스트랩';
update public.products set color_count = 8 where name = '갤럭시 워치8 호환 마그네틱 디버클 슬림 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '갤럭시 워치8 클래식 마그네틱 디버클 슬림 레더 스트랩';
update public.products set color_count = 7 where name = '갤럭시 워치8 호환 빈티지 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 그레이, 네이비, 그린, 오렌지, 옐로우, 브라운' where name = '갤럭시 워치8 클래식 빈티지 레더 스트랩';
update public.products set color_count = 6 where name = '갤럭시 워치8 호환 브리즈 포우 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 실버, 퍼플, 브라운, 베이지' where name = '갤럭시 워치8 클래식 호환 브리즈 포우 레더 스트랩';
update public.products set color_count = 7 where name = '갤럭시 워치8 호환 크로코 클래식 포우 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 네이비, 블루, 레드, 핑크, 브라운' where name = '갤럭시 워치8 클래식 호환 크로코 클래식 포우 레더 스트랩';
update public.products set color_count = 6 where name = '갤럭시 워치8 호환 컴포트 핏 버클 나일론 실리콘 스트랩';
update public.products set color_count = 1, color = '그레이, 블루' where name = '갤럭시 워치8 클래식 호환 컴포트 핏 버클 나일론 실리콘 스트랩';
update public.products set color_count = 20 where name = '갤럭시 워치8 호환 컴포트 핏 디버클 나일론 실리콘 스트랩';
update public.products set color_count = 20, color = '블랙, 그레이, 블루, 그린, 오렌지' where name = '갤럭시 워치8 클래식 호환 컴포트 핏 디버클 나일론 실리콘 스트랩';
update public.products set color_count = 14 where name = '갤럭시 워치8 호환 플렉스 니트 하이브리드 버클 나일론 실리콘 스트랩';
update public.products set color_count = 1, color = '그레이, 블루' where name = '갤럭시 워치8 클래식 호환 플렉스 니트 하이브리드 버클 나일론 실리콘 스트랩';
update public.products set color_count = 17 where name = '갤럭시 워치8 호환 매트 그레인 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 17, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '갤럭시 워치8 클래식 호환 매트 그레인 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 42, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 호환 스트라이프 엣지 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 42, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 클래식 호환 스트라이프 엣지 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 10 where name = '갤럭시 워치8 호환 매시브 메탈 버클 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 오렌지, 옐로우, 핑크, 퍼플' where name = '갤럭시 워치8 클래식 호환 매시브 메탈 버클 실리콘 스트랩';
update public.products set color_count = 26 where name = '갤럭시 워치8 호환 듀오링 스포츠 나일론 스트랩';
update public.products set color_count = 26, color = '블랙, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 클래식 호환 듀오링 스포츠 나일론 스트랩';
update public.products set color_count = 11, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 호환 에어 그리드 애슬레틱 버튼 실리콘 스트랩';
update public.products set color_count = 11, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 클래식 호환 에어 그리드 애슬레틱 버튼 실리콘 스트랩';
update public.products set color_count = 15, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 호환';
update public.products set color_count = 15, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 베이지' where name = '갤럭시 워치8 클래식 호환';
update public.products set color_count = 24, color = '그린, 레드, 옐로우, 핑크, 퍼플' where name = '갤럭시 워치8 호환 버클 파스텔 스트랩';
update public.products set color_count = 24, color = '그린, 레드, 옐로우, 핑크, 퍼플' where name = '갤럭시 워치8 클래식 호환 버클 파스텔 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 오렌지, 옐로우' where name = '갤럭시 워치 울트라 호환 🟩🟩🟩 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 그린, 레드, 오렌지' where name = '갤럭시 워치 울트라 2025 호환 🟩🟩🟩🟩 스트랩';
update public.products set color_count = 12, color = '화이트, 그레이, 그린, 오렌지, 베이지' where name = '갤럭시 워치 울트라 호환 듀오링 스포츠 나일론 스트랩';
update public.products set color_count = 20, color = '블랙, 화이트, 실버, 네이비, 블루, 그린' where name = '갤럭시 워치 울트라 2025 호환 듀오링 스포츠 나일론 스트랩';
update public.products set color_count = 9, color = '블랙, 실버, 골드' where name = '갤럭시 워치 울트라 호환 모딕 메쉬 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 골드' where name = '갤럭시 워치 울트라 2025 호환 모딕 메쉬 메탈 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 호환 매시브 메탈 버클 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 2025 호환 매시브 메탈 버클 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '갤럭시 워치 울트라 호환 스트라이프 엣지 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '갤럭시 워치 울트라 2025 호환 스트라이프 엣지 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 네이비, 블루, 그린, 레드, 옐로우, 퍼플, 브라운, 베이지' where name = '갤럭시 워치 울트라 호환 와이트릭 마그넷 링크 메탈 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 베이지' where name = '갤럭시 워치 울트라 2025 호환 와이트릭 마그넷 링크 메탈 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 그린, 레드, 오렌지' where name = '갤럭시 워치 울트라 2025 호환 오션 마그네틱 버클 프레스티지 스테인리스 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 호환 엑시엄 메탈 버클 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 2025 호환 엑시엄 메탈 버클 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 호환 프레임엑스 일체형 메탈 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 그레이, 네이비, 블루' where name = '갤럭시 워치 울트라 2025 호환 프레임엑스 일체형 메탈 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 핑크, 베이지' where name = '갤럭시워치 울트라 호환 디버클 마그네틱 스포티 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 네이비, 블루, 그린, 오렌지' where name = '갤럭시 위치 울트라 2025 호환 디버클 마그네틱 스포티 실리콘 스트랩';
update public.products set color_count = 19, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 투명' where name = '아머 플렉스 Privacy 사생활 보호 PC 강화유리 올인원 케이스';
update public.products set color_count = 14, color = '블랙, 화이트, 실버, 골드, 레드, 핑크, 퍼플' where name = 'PC 강화유리 올인원 케이스';
update public.products set color_count = 1, color = '실버, 투명' where name = 'TPU 사이드 범퍼 케이스';
update public.products set color_count = 14, color = '블랙, 화이트, 실버, 골드, 레드, 핑크, 퍼플' where name = '탠저린 베젤 강화유리 일체형 올인원 케이스';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 47mm 호환 강화유리 필름 3매';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 2025 47mm 호환 강화유리 필름 3매';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 47mm 호환 TPU 필름 3매';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 2025 47mm 호환 TPU 필름 3매';
update public.products set color_count = 19, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 투명' where name = '갤럭시 워치 울트라 47mm 호환 Privacy 사생활 필름 3매';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 2025 47mm 호환 Privacy 사생활 필름 3매';
update public.products set color_count = 4, color = '투명' where name = '갤럭시 워치 울트라 47mm 호환 PMMA 필름 3매';
update public.products set color_count = 1 where name = 'Privacy 사생활 필름 3매 PMMA 필름 3매';
update public.products set color_count = 12, color = '화이트, 그레이, 그린, 오렌지, 베이지' where name = '갤럭시 위치 울트라 호환 모던 패브릭 나일론 스트랩';
update public.products set color_count = 15, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플, 베이지' where name = '베이직 실리콘 스트랩 2P';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 투명' where name = '스포티 실리콘 스트랩 + TPU 범퍼 케이스';
update public.products set color_count = 10, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 핑크, 베이지' where name = '펀치홀 실리콘 스트랩';
update public.products set color_count = 20, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 베이지' where name = '듀오 매트 그레인 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 레드, 브라운' where name = '하이브리드 레더 실리콘 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 블루, 그린, 핑크' where name = '일체형 컬러 실리콘 스트랩';
update public.products set color_count = 6, color = '블랙, 블루, 레드, 옐로우, 퍼플' where name = '솔라 플립 일체형 스트랩';
update public.products set color_count = 51, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 퍼플' where name = '러기드 아머 일체형 스트랩';
update public.products set color_count = 8, color = '블랙, 그레이, 실버, 네이비, 블루, 그린, 오렌지' where name = '나토 스트랩';
update public.products set color_count = 22, color = '블랙, 화이트, 실버, 네이비, 블루, 그린, 옐로우, 핑크, 퍼플, 베이지' where name = '스포츠 루프 스트랩';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 퍼플, 브라운' where name = '스트레치 스트랩';
update public.products set color_count = 21, color = '블랙, 화이트, 그레이, 블루, 그린, 레드, 옐로우' where name = '트레일 나일론 스트랩';
update public.products set color_count = 24, color = '그린, 레드, 옐로우, 핑크, 퍼플' where name = '마그네틱 버클 파스텔 브레이드 스트랩';
update public.products set color_count = 6 where name = '프리미엄 메탈 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '프리미엄 스틸 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 골드' where name = '링크 브레이슬릿 스틸 스트랩';
update public.products set color_count = 3, color = '블랙, 실버, 골드' where name = '슬림 쥬빌레 메탈 스트랩';
update public.products set color_count = 6, color = '블랙, 실버, 골드' where name = '체인 스틸 메탈 스트랩';
update public.products set color_count = 5, color = '실버, 골드' where name = '샤인 큐빅 슬림 브레이슬릿';
update public.products set color_count = 4, color = '블랙, 실버, 골드, 핑크' where name = '큐빅 브레이슬릿 스트랩';
update public.products set color_count = 5, color = '블랙, 화이트, 브라운, 베이지' where name = '벨라 링크 레더 스트랩';
update public.products set color_count = 6, color = '블랙, 화이트, 그린, 레드, 핑크, 브라운' where name = '모던 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 블루, 그린, 핑크' where name = '트위드 레더 스트랩';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 오렌지, 핑크, 브라운' where name = 'T 버클형 모노 컬러 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '디버클 마그네틱 그레인 레더 스트랩';
update public.products set color_count = 1, color = '핑크' where name = '핏3 호환 샤인큐빅 범퍼 케이스';
update public.products set color_count = 1, color = '실버, 투명' where name = '범퍼 TPU 케이스';
update public.products set color_count = 1, color = '골드, 투명' where name = '풀커버 TPU 케이스';
update public.products set color_count = 14, color = '블랙, 화이트, 실버, 골드, 레드, 핑크, 퍼플' where name = '올인원 PC 케이스';
update public.products set color_count = 1, color = '투명' where name = 'TPU 필름 3매';
update public.products set color_count = 18, color = '블랙, 레드' where name = '핏3 충전케이블 1m USB-A타입';
update public.products set color_count = 2, color = '블랙, 화이트' where name = '핏3 충전케이블 1m USB-C타입';
update public.products set color_count = 6, color = '블랙, 화이트' where name = '갤럭시 핏3 호환 유니버셜 USB-A타입 충전 케이블';
update public.products set color_count = 18, color = '블랙, 레드' where name = '갤럭시 핏3 호환 테크 아트 거치 스탠드 충전 크래들 1m, USB-A타입';
update public.products set color_count = 12 where name = '날개형 웨이브 스티치 실리콘 스트랩 (*스트릿엣지 디자인)';
update public.products set color_count = 44, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 옐로우, 핑크, 퍼플, 베이지' where name = '날개형 ''에어'' 디버클 마그네틱 메쉬홀 실리콘 스트랩 (* 스트릿 엣지 스타일)';
update public.products set color_count = 10, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 레드, 오렌지, 핑크, 베이지' where name = '날개형 소프트 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 4, color = '블랙, 실버, 핑크, 베이지' where name = '날개형 마그넷 링크 실리콘 스트랩';
update public.products set color_count = 2, color = '핑크, 퍼플' where name = '날개형 익스트림 실리콘 스트랩';
update public.products set color_count = 4 where name = '날개형 스페이스핏 스틸 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 실버, 골드, 그린, 레드, 핑크, 퍼플' where name = '날개형 메탈 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 실버, 골드, 그린, 레드, 핑크, 퍼플' where name = '날개형 프리미엄 메탈 스트랩';
update public.products set color_count = 24, color = '그린, 레드, 옐로우, 핑크, 퍼플' where name = '날개형 프리미엄 버클 스틸 스트랩 20mm';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '날개형 베이직 링크 브레이슬릿 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 골드' where name = '날개형 프리미엄 링크 브레이슬릿 스트랩';
update public.products set color_count = 9, color = '블랙, 화이트, 네이비, 그린, 레드, 옐로우, 핑크, 브라운' where name = '날개형 하이브리드 레더 실리콘 스트랩';
update public.products set color_count = 7, color = '화이트, 그레이, 블루, 그린, 오렌지, 핑크, 브라운' where name = '날개형 베이직 가죽 레더 스트랩';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 오렌지, 옐로우' where name = '날개형 콘트라스트 마그네틱 실리콘 스트랩 20mm';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 블루, 그린, 레드, 옐로우, 브라운, 베이지' where name = '날개형 듀얼 쉐이드 마그네틱 실리콘 스트랩 20mm';
update public.products set color_count = 22, color = '블랙, 화이트, 그레이, 실버, 네이비, 그린, 레드, 오렌지' where name = '투톤 마린 오션 실리콘 스트랩';
update public.products set color_count = 4 where name = '원클릭 날개형 베이직 스틸 스트랩';
update public.products set color_count = 3 where name = '원클릭 날개형 프리미엄 스틸 스트랩';
update public.products set color_count = 7, color = '화이트, 그레이, 블루, 그린, 오렌지, 핑크, 브라운' where name = '원클릭 날개형 가죽 스트랩';
update public.products set color_count = 16, color = '블랙, 화이트, 그레이, 네이비, 블루, 오렌지, 핑크, 브라운, 베이지' where name = '원클릭 날개형 싱글 투어 레더 스트랩';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '원클릭 날개형 디버클 슬림 레더 스트랩';
update public.products set color_count = 7, color = '블랙, 그레이, 네이비, 블루, 그린, 오렌지, 옐로우, 브라운' where name = '원클릭 날개형 빈티지 가죽 스트랩';
update public.products set color_count = 20, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플, 베이지' where name = '원클릭 날개형 알파핏 실리콘 스트랩 (소진 시 단종 예정)';
update public.products set color_count = 20 where name = '원클릭 날개형 스포츠 실리콘 스트랩 (알파핏 보강품)';
update public.products set color_count = 15, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 옐로우, 핑크, 퍼플' where name = '원클릭 날개형 다이나믹 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 오렌지, 옐로우, 핑크, 퍼플, 베이지' where name = '원클릭 날개형 웨이브 스티치 실리콘 스트랩 20mm (*참고: 스트릿 엣지 디자인)';
update public.products set color_count = 8, color = '블랙, 실버, 핑크, 퍼플, 브라운' where name = '원클릭 날개형 코도반 레더 가죽 스트랩';
update public.products set color_count = 4 where name = '체인 브레이슬릿 메탈 스트랩';
update public.products set color_count = 4 where name = '비건 레더 싱글 체인 메탈 스트랩';
update public.products set color_count = 5, color = '블랙, 실버, 그린, 핑크, 퍼플, 투명' where name = '일체형 투명 범퍼 케이스 밀레니즈 메탈 스트랩';
update public.products set color_count = 6 where name = '후크 패브릭 나일론 스트랩';
update public.products set color_count = 18 where name = '풀탭 스포츠루프 밸크로 패브릭 나일론 스트랩';
update public.products set color_count = 20, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 옐로우, 핑크, 퍼플, 브라운, 베이지' where name = '모노 스포츠루프 스트랩';
update public.products set color_count = 17 where name = '모노 스포츠루프 스트랩 2P 세트 [블랙+00*]';
update public.products set color_count = 34 where name = '프리미엄 모노 스포츠루프 스트랩';
update public.products set color_count = 12 where name = '브레이드 솔로 루프 밴드 스트랩 (3사이즈)';
update public.products set color_count = 17 where name = '프리미엄 마그네틱 브레이드 스트랩';
update public.products set color_count = 10 where name = '마그네틱 브레이드 스트랩';
update public.products set color_count = 7 where name = '나토 나일론 웨빙 스트랩';
update public.products set color_count = 10 where name = '스포티 실리콘 스트랩 1P';
update public.products set color_count = 10 where name = '스포티 실리콘 스트랩 2P 세트';
update public.products set color_count = 15 where name = '베이직 실리콘 스트랩 1P';
update public.products set color_count = 15 where name = '베이직 실리콘 스트랩 2P 세트';
update public.products set color_count = 10 where name = '마그넷 링크 실리콘 스트랩';
update public.products set color_count = 7 where name = '미밴드 10 올인원 케이스 (* 단독 호환)';
update public.products set color_count = 8 where name = '러기드 스포츠 강화유리 일체형 케이스 (*9 호환)';
update public.products set color_count = 7 where name = '러기드 스포츠 강화유리 PC 하드 케이스 (*10호환)';
update public.products set color_count = 1 where name = 'TPU 풀커버 케이스 (*8~9)';
update public.products set color_count = 3 where name = 'TPU 풀커버 케이스 (*10 단독 호환)';
update public.products set color_count = 11 where name = '샤인 큐빅 범퍼 케이스';
update public.products set color_count = 8, color = '블랙, 실버, 골드, 레드, 핑크, 퍼플' where name = '미밴드 10 네코 블링 캣';
update public.products set color_count = 20, color = '블랙, 실버, 골드, 레드, 핑크, 퍼플' where name = '미밴드 9 네코 블링 캣';
update public.products set color_count = 22, color = '레드, 투명' where name = '아머 플렉스 PMMA 필름 3매';
update public.products set color_count = 22, color = '레드, 투명' where name = '아머 플렉스 TPU 우레탄 자가복원 풀커버 필름 3매';
update public.products set color_count = 16, color = '블랙, 화이트, 레드' where name = '샤오미 미밴드 10 호환 충전 케이블 1m USB-A타입 충전 케이블 1m 시트 참고';
update public.products set color_count = 2 where name = '샤오미 미밴드 10 호환 스틸 스트랩 + 올인원 PC 강화유리 케이스 2in1 세트';
update public.products set color_count = 3 where name = '샤오미 미밴드 10 호환 프리미엄 메탈 스트랩 + 올인원 PC 강화유리 케이스 2in1 세트';
update public.products set color_count = 4 where name = '샤오미 미밴드 10 호환 체인 브레이슬릿 메탈 스트랩 + 샤인 큐빅 범퍼 케이스 2in1 세트';
update public.products set color_count = 9 where name = '샤오미 미밴드 10 호환 프리미엄 모노 스포츠루프 스트랩 + 풀커버 케이스 2in1 세트';
update public.products set color_count = 10 where name = '샤오미 미밴드 10 호환 마그네틱 브레이드 스트랩 + 올인원 PC 강화유리 투명 케이스 2in1 세트';
update public.products set color_count = 12 where name = '샤오미 미밴드 10 호환 베이직 실리콘 스트랩 + 풀커버 케이스 2in1 세트';
update public.products set color_count = 8 where name = '샤오미 미밴드 10 호환 스포티 실리콘 스트랩 + 올인원 PC 강화유리 케이스 2in1 세트';
update public.products set color_count = 9 where name = '샤오미 미밴드 10 호환 에어슬로프 밸크로 나일론 패브릭 스트랩 + 올인원 PC 강화유리 투명 케이스 2in1 세트';
update public.products set color_count = 8, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 퍼플' where name = '어메이즈핏 티렉스 호환 베이직 버클 실리콘 스트랩 (*티렉스 1)';
update public.products set color_count = 7, color = '블랙, 화이트, 그레이, 그린, 레드, 오렌지, 옐로우' where name = '어메이즈핏 티렉스 3 호환 스탠다드 투톤 실리콘 스트랩';
update public.products set color_count = 7, color = '블랙, 화이트, 그레이, 그린, 레드, 오렌지, 옐로우' where name = '어메이즈핏 티렉스 3 호환 스탠다드 버클 실리콘 스트랩';
update public.products set color_count = 13, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 오렌지' where name = '어메이즈핏 티렉스 3 프로 48mm 호환 스탠다드 버클 실리콘 스트랩';
update public.products set color_count = 13, color = '블랙, 화이트, 그레이, 네이비, 블루, 그린, 레드, 오렌지' where name = '어메이즈핏 티렉스 3 프로 44mm 호환 스탠다드 버클 실리콘 스트랩';
update public.products set color_count = 12, color = '블랙, 화이트, 그레이, 실버, 네이비, 블루, 그린, 레드, 오렌지, 핑크' where name = '펀칭 실리콘 스트랩';
update public.products set color_count = 6, color = '블랙, 그레이, 실버, 네이비, 블루, 그린' where name = '컴포트핏 버클 나일론 실리콘 스트랩 22mm (*가제)';
update public.products set color_count = 5, color = '블랙, 그레이, 블루, 그린, 오렌지' where name = '컴포트핏 디버클 나일론 실리콘 스트랩 22mm (*가제)';
update public.products set color_count = 4, color = '블랙, 실버, 골드' where name = '플렉서블 링크 브레이슬릿 스틸 스트랩 22mm';
update public.products set color_count = 32, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 핑크' where name = '런 스플릿 실리콘 스트랩 22mm';
update public.products set color_count = 32, color = '블랙, 화이트, 그레이, 네이비, 그린, 레드, 핑크' where name = '에어그리드 애슬레틱 버튼 실리콘 스트랩 22mm';
